db.getCollectionNames().forEach(function(c) {if(c.indexOf('o_') < 0) return; db.getCollection(c).remove({'m.ts': {'$lt': new Date().getTime() - 5 * 24 * 60 * 60 * 1000}});})
db.getCollectionNames().forEach(function(c) {if(c.indexOf('system') >= 0 || c.indexOf('o_') >= 0 || c.indexOf('sessions') >= 0) return; db.getCollection(c).remove({'_type': {'$type': 10}});})
db.tasks.remove({'createdAt': {'$lt': new Date().getTime() - 60 * 60 * 1000}, 'startTime': {'$exists': false}})
db.o_tasks.remove({'m.ts': {'$lt': new Date().getTime() - 60 * 60 * 1000}})
quit()